src/MovieShop.MVC/Models/ErrorViewModel.cs
namespace MovieShop.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/MovieShop.MVC/Controllers/AccountController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ApplicationCore.Entities;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace MovieShop.MVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ICurrentUserService _currentUserService;
        private readonly IUserService _userService;

        public AccountController(ICurrentUserService currentUserService, IUserService userService,
            IConfiguration config)
        {
            _currentUserService = currentUserService;
            _userService = userService;
            _config = config;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile profileImage)
        {
            var userProfile = new UserProfileRequestModel()
            {
                Id = _currentUserService.UserId.Value,
                FullName = _currentUserService.FullName,
                File = profileImage
            };

            var response = _userService.UploadUserProfilePicture(userProfile);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel registerModel)
        {
            if (!ModelState.IsValid) return View();

            var registeredUser = await _userService.CreateUser(registerModel);

            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Login()
        {
            if (User.Identity != null && User.Identity.IsAuthenticated) return LocalRedirect("~/");
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginRequestModel loginRequest, string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");
            if (!ModelState.IsValid) return View();

            var user = await _userService.ValidateUser(loginRequest.Email, loginRequest.Password);

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Email),
                new Claim(ClaimTypes.GivenName, user.FirstName),
                new Claim(ClaimTypes.Surname, user.LastName),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
            };

            if (user.Roles != null) claims.AddRange(user.Roles.Select(role => new Claim(ClaimTypes.Role, role.Name)));

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));

            return LocalRedirect(returnUrl);
        }
    }
}

src/MovieShop.MVC/Controllers/AdminController.cs
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public AdminController(IUserService userService, IMovieService movieService)
        {
            _userService = userService;
            _movieService = movieService;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> CreateMovie()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMovie(MovieCreateRequest movieCreateRequest)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var createdMovie = await _movieService.CreateMovie(movieCreateRequest);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CreateCast()
        {
            return View();
        }
    }
}

src/MovieShop.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShop.MVC.Models;

namespace MovieShop.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieService _movieService;

        public HomeController(ILogger<HomeController> logger, IMovieService movieService)
        {
            _logger = logger;
            _movieService = movieService;
        }

        public async Task<IActionResult> Index()
        {
            var topGrossingMovies = await _movieService.GetHighestGrossingMovies();
            return View(topGrossingMovies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

src/MovieShop.MVC/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Genre(int id, int pageSize = 30, int pageNumber = 1)
        {
            var movies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedIndex", movies);
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieAsync(id);
            return View(movie);
        }
    }
}

src/MovieShop.MVC/Controllers/UserController.cs
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public UserController(IUserService userService, IMovieService movieService)
        {
            _userService = userService;
            _movieService = movieService;
        }

        [HttpGet]
        public async Task<IActionResult> BuyMovie(int id)
        {
            var movie = await _movieService.GetMovieAsync(id);
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> BuyMovie(PurchaseRequestModel purchase)
        {
            await _userService.PurchaseMovie(purchase);
            return Ok();
        }
    }
}

src/MovieShop.MVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace MovieShop.MVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent:ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }
    }
}

src/MovieShop.MVC/Views/Admin/CreateMovie.cshtml
@using ApplicationCore.ServiceInterfaces
@model ApplicationCore.Models.MovieCreateRequest
@inject IGenreService GenreService;
@{
    ViewData["Title"] = "CreateView";
}

<h3>Create Movie</h3>

<hr/>
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="CreateMovie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Overview"></label>
                <input asp-for="Overview" class="form-control"/>
                <span asp-validation-for="Overview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tagline"></label>
                <input asp-for="Tagline" class="form-control"/>
                <span asp-validation-for="Tagline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Revenue"></label>
                <input asp-for="Revenue" class="form-control"/>
                <span asp-validation-for="Revenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Budget"></label>
                <input asp-for="Budget" class="form-control"/>
                <span asp-validation-for="Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImdbUrl"></label>
                <input asp-for="ImdbUrl" class="form-control"/>
                <span asp-validation-for="ImdbUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TmdbUrl"></label>
                <input asp-for="TmdbUrl" class="form-control"/>
                <span asp-validation-for="TmdbUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PosterUrl"></label>
                <input asp-for="PosterUrl" class="form-control"/>
                <span asp-validation-for="PosterUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackdropUrl"></label>
                <input asp-for="BackdropUrl" class="form-control"/>
                <span asp-validation-for="BackdropUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginalLanguage"></label>
                <input asp-for="OriginalLanguage" class="form-control"/>
                <span asp-validation-for="OriginalLanguage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate"></label>
                <input asp-for="ReleaseDate" class="form-control"/>
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RunTime"></label>
                <input asp-for="RunTime" class="form-control"/>
                <span asp-validation-for="RunTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="CreateMovie" class="btn btn-primary">
                    Create Movie
                </button>
            </div>
        </form>
    </div>


</div>
<div class="row justify-content-center">
    <h5 class="mb-2">Genres</h5>
    <div class="form-check col-md-4">

        @foreach (var genre in await GenreService.GetAllGenres())
        {
            <input name="genre" type="checkbox" value="@genre.Id"/>
            @genre.Name<br/>
        }
    </div>

</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/MovieShop.MVC/Views/Home/Index.cshtml
@model IEnumerable<ApplicationCore.Models.MovieResponseModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @*<partial name="MovieCard" model="movie"/>*@
                    @await Html.PartialAsync("_MovieCard", movie)
                </div>
            }

        </div>
    </div>
</div>

src/MovieShop.MVC/Views/Movies/Details.cshtml
@inject ICurrentUserService UserService
@using System.Globalization
@using ApplicationCore.ServiceInterfaces
@model ApplicationCore.Models.MovieDetailsResponseModel
<div class="bg-image" style="background-image: url(@Model.BackdropUrl)">

    <div class="row">
        <div class="col-md-3 offset-2">

            <!-- Movie Card row -->
            <div>
                <img src="@Model.PosterUrl" class="card-img-top"/>
            </div>

        </div>
        <div class="col-md-4">
            <div class="row mt-2">
                <div class="col-12">
                    <h1 class="text-white">
                        @Model.Title
                    </h1>
                    <small class="text-muted"> @Model.Tagline </small>
                </div>

            </div>

            <div class="row">
                <div class="col-4 text-secondary font-weight-bold mt-2">
                    @Model.RunTime m | @Model.ReleaseDate.Value.Date.Year
                </div>
                <div class="col-8">

                    @foreach (var genre in Model.Genres)
                    {
                        <a class="badge badge-pill badge-dark ml-1" asp-action="Genre" asp-route-id="@genre.Id">
                            @genre.Name
                        </a>
                    }
                </div>
            </div>

            <div class="row">
                <div class="col-4 mt-3">
                    <h4>
                        <span class="badge badge-warning">
                            @Model.Rating?.ToString("0.00")
                        </span>
                    </h4>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-light mt-2">
                    @Model.Overview
                </div>
            </div>
        </div>

        <div class="col-md-2 mt-4 offset-1">
            <ul class="list-group">
                <li class="list-group-item">


                </li>
                <li class="list-group-item">
                    <button type="button"
                            class="btn btn-outline-light btn-lg btn-block btn-sm">
                        <i class="far fa-edit mr-1"></i>
                        REVIEW
                    </button>
                </li>
                <li class="list-group-item">
                    <button type="button"
                            class="btn btn-outline-light btn-lg btn-block btn-sm">
                        <i class="fas fa-play mr-1"></i> TRAILER
                    </button>
                </li>

                <li class="list-group-item">
                    <a class="btn btn-light btn-lg btn-block btn-sm" asp-route-id="@Model.Id" asp-controller="User" asp-action="BuyMovie">
                        BUY @Model.Price
                    </a>

                    <a class="btn btn-light btn-lg btn-block btn-sm" asp-route-id="@Model.Id" asp-controller="User" asp-action="BuyMovie">
                        WATCH MOVIE
                    </a>
                </li>
            </ul>
        </div>

    </div>
</div>


<div class="row mt-4">
    <div class="col-4 moviefacts">
        <h5>MOVIE FACTS</h5>
        <hr>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <i class="far fa-calendar-alt mr-2"></i>Release Date
                <span class="badge badge-pill badge-dark">@Model.ReleaseDate.Value.ToShortDateString()</span>
            </li>

            <li class="list-group-item">
                <i class="fas fa-hourglass-half mr-2"></i>Run Time
                <span class="badge badge-pill badge-dark">@Model.RunTime.Value m</span>
            </li>
            <li class="list-group-item">
                <i class="far fa-money-bill-alt"></i> Box Office
                <span class="badge badge-pill badge-pill badge-dark">
                    @NumberFormatInfo.CurrentInfo.CurrencySymbol
                    @Model.Revenue?.ToString("C0")
                </span>
            </li>

            <li class="list-group-item">
                <i class="fas fa-dollar-sign mr-2"></i> Budget
                <span class="badge badge-pill badge-dark">
                    @NumberFormatInfo.CurrentInfo.CurrencySymbol
                    @Model.Budget?.ToString("C0")
                </span>
            </li>

            <li class="list-group-item">
                <i class="fab fa-imdb"></i>

                <a href="@Model.ImdbUrl"
                   class="text-dark ml-3"
                   target="_blank">
                    <i class="fas fa-share-square mr-2"></i>
                </a>
            </li>

        </ul>
    </div>

    <div class="col-4 offset-1">
        <h5>CAST</h5>

        <table class="table">

            <tbody>


            @foreach (var cast in Model?.Casts)
            {
                <tr>
                    <td>
                        <img src="@cast.ProfilePath"
                             class="cast-small-img rounded-circle"
                             alt="@cast.Name"/>
                    </td>
                    <td> @cast.Name </td>
                    <td> @cast.Character</td>
                </tr>
            }


            </tbody>
        </table>

    </div>
</div>

src/MovieShop.MVC/Views/Movies/PagedIndex.cshtml
@model ApplicationCore.Helpers.PaginatedList<ApplicationCore.Models.MovieResponseModel>

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @*<partial name="MovieCard" model="movie"/>*@
                    @await Html.PartialAsync("_MovieCard", movie)
                </div>
            }

        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Genre"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   class="btn btn-primary @prevDisabled">
    Previous
</a>
<a asp-action="Genre"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   class="btn btn-primary @nextDisabled">
    Next
</a>

src/MovieShop.MVC/Views/Shared/Components/Genres/Default.cshtml
@model IEnumerable<ApplicationCore.Models.GenreModel>


@foreach (var genre in Model)
{
    @*@Html.ActionLink(genre.Name, "Genre", "Movies", new { genreId = genre.Id }, new { @class = "dropdown-item" })*@

    <a asp-action="genre" asp-controller="Movies" class="dropdown-item" asp-route-id="@genre.Id"> @genre.Name</a>
}

src/MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Movie Shop</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav mr-auto text-uppercase">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Genres
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @await Component.InvokeAsync("Genres")
                    </div>
                </li>
            </ul>
        </div>
        <div class="navbar-collapse collapse w-100 order-3">
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

        <partial name="_LoginPartial"/>

    </nav>
</header>
<div class="container-fluid mt-1">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    @*<div class="container">
        &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>*@
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", false)
<script>
    //$('form').one('submit',
    //    function () {
    //        console.log($('form').valid());
    //        $(this).find('button[type="submit"]').attr('disabled', 'disabled')
    //            .append('  <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>');
    //    });
</script>
</body>
</html>

src/MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>

src/MovieShop.MVC/Views/User/BuyMovie.cshtml
@inject ICurrentUserService CurrentUserService
@using ApplicationCore.ServiceInterfaces
@model ApplicationCore.Models.MovieDetailsResponseModel


<form method="post" asp-controller="User" asp-action="BuyMovie">
    <div class="card mb-3 container shadow ">
        <div class="row justify-content-md-center">
            <div class="col-md-4">
                <img src="@Model.PosterUrl" alt="@Model.Title" class="card-img-top">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5>Order Summary</h5>
                    <hr/>
                    <div class="row">
                        <div class="col-md-6 h5">
                            @Model.Title
                        </div>
                        <div class="col-md-6 h5">
                            $@Model.Price
                        </div>
                        <div class="col-12" >
                            <input type="submit" value="Confirm Purchase" class="btn btn-primary btn-lg btn-block"/>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</form>